# docker compose up -d

services:
  # gremlin-console:
  #   image: tinkerpop/gremlin-console:latest
  #   platform: linux/x86_64
  #   user: "1000:1000"
  #   links:
  #     - gremlin-server
  #   command: "-i conf/remote.groovy"
  #   volumes:
  #     - ./gremlin-console/conf:/opt/gremlin-console/conf:r

  gremlin-server:
    image: tinkerpop/gremlin-server:latest
    restart: always
    platform: linux/x86_64
    user: "1000:1000"
    ports:
      - "8182:8182"
    volumes:
      - ./gremlin-server/conf:/opt/gremlin-server/conf:ro
      - graph-data:/opt/gremlin-server/data:rw

volumes:
  graph-data:
